//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amana940Complain
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Amana940Complain.AmanaReceiverSoap")]
    public interface AmanaReceiverSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddComplaints", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Amana940Complain.ReplyMessages> AddComplaintsAsync(string xCustomerPhone, string xCustomerName, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, int xViaID, string xUserName, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddComplaintsWithHiddenField", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Amana940Complain.ReplyMessages> AddComplaintsWithHiddenFieldAsync(string xCustomerPhone, string xCustomerName, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, int xViaID, string xHiddenField, string xUserName, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewMomraIncedent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Amana940Complain.ReplyMessages> AddNewMomraIncedentAsync(string xCustomerPhone, string xCustomerName, string xClassificationDesc, string xClassificationID, string xIncidentDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, string xIncidentNO, string xUserName, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddComplaintsWithSubCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Amana940Complain.ReplyMessages> AddComplaintsWithSubCategoryAsync(string xCustomerPhone, string xCustomerName, string xCategoryID, string xSubCategoryID, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, int xViaID, string xHiddenField, string xUserName, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchComplaints", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Amana940Complain.Complains[]> SearchComplaintsAsync(string xCustomerPhone, string xProblemsNumber, string xProblemStatusID, string xPageIndex, string xPageSize, string xUserName, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetComplaintActionsHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Amana940Complain.ComplainsActionHistory[]> GetComplaintActionsHistoryAsync(string xRefKey, string xUserName, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchComplaintsByViaID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Amana940Complain.Complains[]> SearchComplaintsByViaIDAsync(string xCustomerPhone, string xProblemsNumber, string xProblemStatusID, string xViaID, string xStartDate, string xEndDate, string xPageIndex, string xPageSize, string xUserName, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComplaintAttachmentDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Amana940Complain.ComplaintAttachmentDetails[]> ComplaintAttachmentDetailsAsync(string xComplaintNumber, string xUserName, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MomraIncidentDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Amana940Complain.MomraIncident[]> MomraIncidentDetailsAsync(string xIncidentNO, string xUserName, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComplaintDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Amana940Complain.ComplaintDetails[]> ComplaintDetailsAsync(string xCustomerPhone, string xProblemsNumber, string xUserName, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComplaintDetailsWithImages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Amana940Complain.ComplaintDetails[]> ComplaintDetailsWithImagesAsync(string xCustomerPhone, string xProblemsNumber, string xUserName, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProblemStatusForAtYourService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Amana940Complain.ReplyMessages> UpdateProblemStatusForAtYourServiceAsync(string xProblemNumber, string xUserName, string xNotes, string xStatusID, string xImage, string xWebErvicePassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateComplaintStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Amana940Complain.ReplyMessages> UpdateComplaintStatusAsync(string xProblemNumber, string xUserName, string xUserPassword, string xNotes, string xStatusID, string xImage, string xWebErvicePassword);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReplyMessages
    {
        
        private int codeField;
        
        private string messageArField;
        
        private string messageEnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageAr
        {
            get
            {
                return this.messageArField;
            }
            set
            {
                this.messageArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MessageEn
        {
            get
            {
                return this.messageEnField;
            }
            set
            {
                this.messageEnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ComplaintDetails
    {
        
        private string short_DescField;
        
        private string problem_DescField;
        
        private string organization_DescArField;
        
        private string subCategory_DescArField;
        
        private string ticket_AddressField;
        
        private string customerContact_ContactDescField;
        
        private string district_DescArField;
        
        private string street_DescArField;
        
        private string problem_CreatedDateField;
        
        private string problem_ClosedDateField;
        
        private string problem_ProblemNumberField;
        
        private string category_DescArField;
        
        private string problemStatus_DescArField;
        
        private int problemStatusIDField;
        
        private int itemsCountField;
        
        private int totalComplainsCountField;
        
        private string problem_LatitudeField;
        
        private string problem_LongitudeField;
        
        private string problem_MobileImagePathField;
        
        private string problem_EvalValueField;
        
        private string problem_ServiceAgreementField;
        
        private string problem_EvalDescField;
        
        private string problem_MobileImageField;
        
        private string problem_MobileVideoField;
        
        private string problem_MobileVoiceField;
        
        private string problem_containsmobileimageField;
        
        private string problem_containsmobilevideoField;
        
        private string problem_containsmobilevoiceField;
        
        private int problem_MobileEvalValueField;
        
        private string problem_ExecutionImageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Short_Desc
        {
            get
            {
                return this.short_DescField;
            }
            set
            {
                this.short_DescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Problem_Desc
        {
            get
            {
                return this.problem_DescField;
            }
            set
            {
                this.problem_DescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Organization_DescAr
        {
            get
            {
                return this.organization_DescArField;
            }
            set
            {
                this.organization_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SubCategory_DescAr
        {
            get
            {
                return this.subCategory_DescArField;
            }
            set
            {
                this.subCategory_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Ticket_Address
        {
            get
            {
                return this.ticket_AddressField;
            }
            set
            {
                this.ticket_AddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CustomerContact_ContactDesc
        {
            get
            {
                return this.customerContact_ContactDescField;
            }
            set
            {
                this.customerContact_ContactDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string District_DescAr
        {
            get
            {
                return this.district_DescArField;
            }
            set
            {
                this.district_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Street_DescAr
        {
            get
            {
                return this.street_DescArField;
            }
            set
            {
                this.street_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Problem_CreatedDate
        {
            get
            {
                return this.problem_CreatedDateField;
            }
            set
            {
                this.problem_CreatedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Problem_ClosedDate
        {
            get
            {
                return this.problem_ClosedDateField;
            }
            set
            {
                this.problem_ClosedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Problem_ProblemNumber
        {
            get
            {
                return this.problem_ProblemNumberField;
            }
            set
            {
                this.problem_ProblemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Category_DescAr
        {
            get
            {
                return this.category_DescArField;
            }
            set
            {
                this.category_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ProblemStatus_DescAr
        {
            get
            {
                return this.problemStatus_DescArField;
            }
            set
            {
                this.problemStatus_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int ProblemStatusID
        {
            get
            {
                return this.problemStatusIDField;
            }
            set
            {
                this.problemStatusIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int ItemsCount
        {
            get
            {
                return this.itemsCountField;
            }
            set
            {
                this.itemsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int TotalComplainsCount
        {
            get
            {
                return this.totalComplainsCountField;
            }
            set
            {
                this.totalComplainsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Problem_Latitude
        {
            get
            {
                return this.problem_LatitudeField;
            }
            set
            {
                this.problem_LatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Problem_Longitude
        {
            get
            {
                return this.problem_LongitudeField;
            }
            set
            {
                this.problem_LongitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Problem_MobileImagePath
        {
            get
            {
                return this.problem_MobileImagePathField;
            }
            set
            {
                this.problem_MobileImagePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Problem_EvalValue
        {
            get
            {
                return this.problem_EvalValueField;
            }
            set
            {
                this.problem_EvalValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Problem_ServiceAgreement
        {
            get
            {
                return this.problem_ServiceAgreementField;
            }
            set
            {
                this.problem_ServiceAgreementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Problem_EvalDesc
        {
            get
            {
                return this.problem_EvalDescField;
            }
            set
            {
                this.problem_EvalDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Problem_MobileImage
        {
            get
            {
                return this.problem_MobileImageField;
            }
            set
            {
                this.problem_MobileImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Problem_MobileVideo
        {
            get
            {
                return this.problem_MobileVideoField;
            }
            set
            {
                this.problem_MobileVideoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Problem_MobileVoice
        {
            get
            {
                return this.problem_MobileVoiceField;
            }
            set
            {
                this.problem_MobileVoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string problem_containsmobileimage
        {
            get
            {
                return this.problem_containsmobileimageField;
            }
            set
            {
                this.problem_containsmobileimageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string problem_containsmobilevideo
        {
            get
            {
                return this.problem_containsmobilevideoField;
            }
            set
            {
                this.problem_containsmobilevideoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string problem_containsmobilevoice
        {
            get
            {
                return this.problem_containsmobilevoiceField;
            }
            set
            {
                this.problem_containsmobilevoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public int Problem_MobileEvalValue
        {
            get
            {
                return this.problem_MobileEvalValueField;
            }
            set
            {
                this.problem_MobileEvalValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Problem_ExecutionImage
        {
            get
            {
                return this.problem_ExecutionImageField;
            }
            set
            {
                this.problem_ExecutionImageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MomraIncident
    {
        
        private string amanaIncidentNoField;
        
        private string incidentNoField;
        
        private int incidentStatusIDField;
        
        private string actionDateField;
        
        private string actionDescriptionField;
        
        private string department_NameField;
        
        private string slaFlagField;
        
        private string evaluationFlagField;
        
        private string evaluationDescriptionField;
        
        private ListItem[] incidentImageAfterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AmanaIncidentNo
        {
            get
            {
                return this.amanaIncidentNoField;
            }
            set
            {
                this.amanaIncidentNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IncidentNo
        {
            get
            {
                return this.incidentNoField;
            }
            set
            {
                this.incidentNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IncidentStatusID
        {
            get
            {
                return this.incidentStatusIDField;
            }
            set
            {
                this.incidentStatusIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ActionDate
        {
            get
            {
                return this.actionDateField;
            }
            set
            {
                this.actionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ActionDescription
        {
            get
            {
                return this.actionDescriptionField;
            }
            set
            {
                this.actionDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Department_Name
        {
            get
            {
                return this.department_NameField;
            }
            set
            {
                this.department_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SlaFlag
        {
            get
            {
                return this.slaFlagField;
            }
            set
            {
                this.slaFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string EvaluationFlag
        {
            get
            {
                return this.evaluationFlagField;
            }
            set
            {
                this.evaluationFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string EvaluationDescription
        {
            get
            {
                return this.evaluationDescriptionField;
            }
            set
            {
                this.evaluationDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public ListItem[] IncidentImageAfter
        {
            get
            {
                return this.incidentImageAfterField;
            }
            set
            {
                this.incidentImageAfterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListItem
    {
        
        private bool enabledField;
        
        private bool selectedField;
        
        private string textField;
        
        private string valueField;
        
        public ListItem()
        {
            this.enabledField = true;
            this.selectedField = false;
            this.textField = "";
            this.valueField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Selected
        {
            get
            {
                return this.selectedField;
            }
            set
            {
                this.selectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ComplaintAttachmentDetails
    {
        
        private bool containsUserImageField;
        
        private bool containsUservideoField;
        
        private bool containsUservoiceField;
        
        private bool containsExecutionAttachmentField;
        
        private ListItem[] executionAttachmentListField;
        
        private ListItem[] userAttachmentListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ContainsUserImage
        {
            get
            {
                return this.containsUserImageField;
            }
            set
            {
                this.containsUserImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool ContainsUservideo
        {
            get
            {
                return this.containsUservideoField;
            }
            set
            {
                this.containsUservideoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool ContainsUservoice
        {
            get
            {
                return this.containsUservoiceField;
            }
            set
            {
                this.containsUservoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ContainsExecutionAttachment
        {
            get
            {
                return this.containsExecutionAttachmentField;
            }
            set
            {
                this.containsExecutionAttachmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public ListItem[] ExecutionAttachmentList
        {
            get
            {
                return this.executionAttachmentListField;
            }
            set
            {
                this.executionAttachmentListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public ListItem[] UserAttachmentList
        {
            get
            {
                return this.userAttachmentListField;
            }
            set
            {
                this.userAttachmentListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ComplainsActionHistory
    {
        
        private string problemActionIDField;
        
        private string problemAction_ProblemNumberField;
        
        private string problemAction_DescField;
        
        private string actionType_DescField;
        
        private string problemAction_CreateDateField;
        
        private string user_FullNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProblemActionID
        {
            get
            {
                return this.problemActionIDField;
            }
            set
            {
                this.problemActionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProblemAction_ProblemNumber
        {
            get
            {
                return this.problemAction_ProblemNumberField;
            }
            set
            {
                this.problemAction_ProblemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ProblemAction_Desc
        {
            get
            {
                return this.problemAction_DescField;
            }
            set
            {
                this.problemAction_DescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ActionType_Desc
        {
            get
            {
                return this.actionType_DescField;
            }
            set
            {
                this.actionType_DescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ProblemAction_CreateDate
        {
            get
            {
                return this.problemAction_CreateDateField;
            }
            set
            {
                this.problemAction_CreateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string User_FullName
        {
            get
            {
                return this.user_FullNameField;
            }
            set
            {
                this.user_FullNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Complains
    {
        
        private string short_DescField;
        
        private string problem_DescField;
        
        private string organization_DescArField;
        
        private string subCategory_DescArField;
        
        private string ticket_AddressField;
        
        private string customerContact_ContactDescField;
        
        private string district_DescArField;
        
        private string street_DescArField;
        
        private string problem_CreatedDateField;
        
        private string problem_ClosedDateField;
        
        private string problem_ProblemNumberField;
        
        private string category_DescArField;
        
        private string problemStatus_DescArField;
        
        private int problemStatusIDField;
        
        private int itemsCountField;
        
        private int totalComplainsCountField;
        
        private string problem_LatitudeField;
        
        private string problem_LongitudeField;
        
        private string problem_MobileImagePathField;
        
        private string problem_RefKeyField;
        
        private string problem_EvalValueField;
        
        private string problem_HiddenFieldIDField;
        
        private string problem_ServiceAgreementField;
        
        private string problem_containsmobileimageField;
        
        private string problem_containsmobilevideoField;
        
        private string problem_containsmobilevoiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Short_Desc
        {
            get
            {
                return this.short_DescField;
            }
            set
            {
                this.short_DescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Problem_Desc
        {
            get
            {
                return this.problem_DescField;
            }
            set
            {
                this.problem_DescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Organization_DescAr
        {
            get
            {
                return this.organization_DescArField;
            }
            set
            {
                this.organization_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SubCategory_DescAr
        {
            get
            {
                return this.subCategory_DescArField;
            }
            set
            {
                this.subCategory_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Ticket_Address
        {
            get
            {
                return this.ticket_AddressField;
            }
            set
            {
                this.ticket_AddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CustomerContact_ContactDesc
        {
            get
            {
                return this.customerContact_ContactDescField;
            }
            set
            {
                this.customerContact_ContactDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string District_DescAr
        {
            get
            {
                return this.district_DescArField;
            }
            set
            {
                this.district_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Street_DescAr
        {
            get
            {
                return this.street_DescArField;
            }
            set
            {
                this.street_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Problem_CreatedDate
        {
            get
            {
                return this.problem_CreatedDateField;
            }
            set
            {
                this.problem_CreatedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Problem_ClosedDate
        {
            get
            {
                return this.problem_ClosedDateField;
            }
            set
            {
                this.problem_ClosedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Problem_ProblemNumber
        {
            get
            {
                return this.problem_ProblemNumberField;
            }
            set
            {
                this.problem_ProblemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Category_DescAr
        {
            get
            {
                return this.category_DescArField;
            }
            set
            {
                this.category_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ProblemStatus_DescAr
        {
            get
            {
                return this.problemStatus_DescArField;
            }
            set
            {
                this.problemStatus_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int ProblemStatusID
        {
            get
            {
                return this.problemStatusIDField;
            }
            set
            {
                this.problemStatusIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int ItemsCount
        {
            get
            {
                return this.itemsCountField;
            }
            set
            {
                this.itemsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int TotalComplainsCount
        {
            get
            {
                return this.totalComplainsCountField;
            }
            set
            {
                this.totalComplainsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Problem_Latitude
        {
            get
            {
                return this.problem_LatitudeField;
            }
            set
            {
                this.problem_LatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Problem_Longitude
        {
            get
            {
                return this.problem_LongitudeField;
            }
            set
            {
                this.problem_LongitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Problem_MobileImagePath
        {
            get
            {
                return this.problem_MobileImagePathField;
            }
            set
            {
                this.problem_MobileImagePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Problem_RefKey
        {
            get
            {
                return this.problem_RefKeyField;
            }
            set
            {
                this.problem_RefKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Problem_EvalValue
        {
            get
            {
                return this.problem_EvalValueField;
            }
            set
            {
                this.problem_EvalValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Problem_HiddenFieldID
        {
            get
            {
                return this.problem_HiddenFieldIDField;
            }
            set
            {
                this.problem_HiddenFieldIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Problem_ServiceAgreement
        {
            get
            {
                return this.problem_ServiceAgreementField;
            }
            set
            {
                this.problem_ServiceAgreementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string problem_containsmobileimage
        {
            get
            {
                return this.problem_containsmobileimageField;
            }
            set
            {
                this.problem_containsmobileimageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string problem_containsmobilevideo
        {
            get
            {
                return this.problem_containsmobilevideoField;
            }
            set
            {
                this.problem_containsmobilevideoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string problem_containsmobilevoice
        {
            get
            {
                return this.problem_containsmobilevoiceField;
            }
            set
            {
                this.problem_containsmobilevoiceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface AmanaReceiverSoapChannel : Amana940Complain.AmanaReceiverSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class AmanaReceiverSoapClient : System.ServiceModel.ClientBase<Amana940Complain.AmanaReceiverSoap>, Amana940Complain.AmanaReceiverSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AmanaReceiverSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AmanaReceiverSoapClient.GetBindingForEndpoint(endpointConfiguration), AmanaReceiverSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AmanaReceiverSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AmanaReceiverSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AmanaReceiverSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AmanaReceiverSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AmanaReceiverSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Amana940Complain.ReplyMessages> AddComplaintsAsync(string xCustomerPhone, string xCustomerName, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, int xViaID, string xUserName, string xPassword)
        {
            return base.Channel.AddComplaintsAsync(xCustomerPhone, xCustomerName, xComplainDescription, xAddressDesc, xLatitude, xLongitude, xImage, xViaID, xUserName, xPassword);
        }
        
        public System.Threading.Tasks.Task<Amana940Complain.ReplyMessages> AddComplaintsWithHiddenFieldAsync(string xCustomerPhone, string xCustomerName, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, int xViaID, string xHiddenField, string xUserName, string xPassword)
        {
            return base.Channel.AddComplaintsWithHiddenFieldAsync(xCustomerPhone, xCustomerName, xComplainDescription, xAddressDesc, xLatitude, xLongitude, xImage, xViaID, xHiddenField, xUserName, xPassword);
        }
        
        public System.Threading.Tasks.Task<Amana940Complain.ReplyMessages> AddNewMomraIncedentAsync(string xCustomerPhone, string xCustomerName, string xClassificationDesc, string xClassificationID, string xIncidentDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, string xIncidentNO, string xUserName, string xPassword)
        {
            return base.Channel.AddNewMomraIncedentAsync(xCustomerPhone, xCustomerName, xClassificationDesc, xClassificationID, xIncidentDescription, xAddressDesc, xLatitude, xLongitude, xImage, xIncidentNO, xUserName, xPassword);
        }
        
        public System.Threading.Tasks.Task<Amana940Complain.ReplyMessages> AddComplaintsWithSubCategoryAsync(string xCustomerPhone, string xCustomerName, string xCategoryID, string xSubCategoryID, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, int xViaID, string xHiddenField, string xUserName, string xPassword)
        {
            return base.Channel.AddComplaintsWithSubCategoryAsync(xCustomerPhone, xCustomerName, xCategoryID, xSubCategoryID, xComplainDescription, xAddressDesc, xLatitude, xLongitude, xImage, xViaID, xHiddenField, xUserName, xPassword);
        }
        
        public System.Threading.Tasks.Task<Amana940Complain.Complains[]> SearchComplaintsAsync(string xCustomerPhone, string xProblemsNumber, string xProblemStatusID, string xPageIndex, string xPageSize, string xUserName, string xPassword)
        {
            return base.Channel.SearchComplaintsAsync(xCustomerPhone, xProblemsNumber, xProblemStatusID, xPageIndex, xPageSize, xUserName, xPassword);
        }
        
        public System.Threading.Tasks.Task<Amana940Complain.ComplainsActionHistory[]> GetComplaintActionsHistoryAsync(string xRefKey, string xUserName, string xPassword)
        {
            return base.Channel.GetComplaintActionsHistoryAsync(xRefKey, xUserName, xPassword);
        }
        
        public System.Threading.Tasks.Task<Amana940Complain.Complains[]> SearchComplaintsByViaIDAsync(string xCustomerPhone, string xProblemsNumber, string xProblemStatusID, string xViaID, string xStartDate, string xEndDate, string xPageIndex, string xPageSize, string xUserName, string xPassword)
        {
            return base.Channel.SearchComplaintsByViaIDAsync(xCustomerPhone, xProblemsNumber, xProblemStatusID, xViaID, xStartDate, xEndDate, xPageIndex, xPageSize, xUserName, xPassword);
        }
        
        public System.Threading.Tasks.Task<Amana940Complain.ComplaintAttachmentDetails[]> ComplaintAttachmentDetailsAsync(string xComplaintNumber, string xUserName, string xPassword)
        {
            return base.Channel.ComplaintAttachmentDetailsAsync(xComplaintNumber, xUserName, xPassword);
        }
        
        public System.Threading.Tasks.Task<Amana940Complain.MomraIncident[]> MomraIncidentDetailsAsync(string xIncidentNO, string xUserName, string xPassword)
        {
            return base.Channel.MomraIncidentDetailsAsync(xIncidentNO, xUserName, xPassword);
        }
        
        public System.Threading.Tasks.Task<Amana940Complain.ComplaintDetails[]> ComplaintDetailsAsync(string xCustomerPhone, string xProblemsNumber, string xUserName, string xPassword)
        {
            return base.Channel.ComplaintDetailsAsync(xCustomerPhone, xProblemsNumber, xUserName, xPassword);
        }
        
        public System.Threading.Tasks.Task<Amana940Complain.ComplaintDetails[]> ComplaintDetailsWithImagesAsync(string xCustomerPhone, string xProblemsNumber, string xUserName, string xPassword)
        {
            return base.Channel.ComplaintDetailsWithImagesAsync(xCustomerPhone, xProblemsNumber, xUserName, xPassword);
        }
        
        public System.Threading.Tasks.Task<Amana940Complain.ReplyMessages> UpdateProblemStatusForAtYourServiceAsync(string xProblemNumber, string xUserName, string xNotes, string xStatusID, string xImage, string xWebErvicePassword)
        {
            return base.Channel.UpdateProblemStatusForAtYourServiceAsync(xProblemNumber, xUserName, xNotes, xStatusID, xImage, xWebErvicePassword);
        }
        
        public System.Threading.Tasks.Task<Amana940Complain.ReplyMessages> UpdateComplaintStatusAsync(string xProblemNumber, string xUserName, string xUserPassword, string xNotes, string xStatusID, string xImage, string xWebErvicePassword)
        {
            return base.Channel.UpdateComplaintStatusAsync(xProblemNumber, xUserName, xUserPassword, xNotes, xStatusID, xImage, xWebErvicePassword);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AmanaReceiverSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AmanaReceiverSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AmanaReceiverSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.call940.sa/Amana940Integration/AmanaReceiver.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AmanaReceiverSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.call940.sa/Amana940Integration/AmanaReceiver.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AmanaReceiverSoap,
            
            AmanaReceiverSoap12,
        }
    }
}
