//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmanaIntegration
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AmanaIntegration.AmanaReceiverMobileSoap")]
    public interface AmanaReceiverMobileSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActivateMobileNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> ActivateMobileNumberAsync(string xCutomerName, string xCustomerPhone, string xDeviceType, string xUserName, string xPassword, string xToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveComplaintsNew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> ReceiveComplaintsNewAsync(string xCustomerPhone, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xAttachmentNo1, string xAttachmentNo1Type, string xAttachmentNo2, string xAttachmentNo2Type, string xAttachmentNo3, string xAttachmentNo3Type, string xUserName, string xPassword, string xToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOTP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> SendOTPAsync(string xCutomerName, string xCustomerPhone, string xDeviceType, string xUserName, string xPassword, string xToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CategoryList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.Category[]> CategoryListAsync(string xUserName, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubCategoryList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.SubCategory[]> SubCategoryListAsync(string xCategoryID, string xUserName, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestInsertNotification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> TestInsertNotificationAsync(string xNotificationArabic, string xNotificationEnglish, string xExpiryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNotification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> SendNotificationAsync(string xUserName, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckOTP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> CheckOTPAsync(string xCustomerPhone, string xOTP, string xUserName, string xPassword, string xToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeactivateMobileNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> DeactivateMobileNumberAsync(string xCustomerPhone, string xUserName, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserIsBlocked", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> CheckUserIsBlockedAsync(string xCustomerPhone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveComplainsWSE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> ReceiveComplainsWSEAsync(string xCustomerPhone, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, string xVideo, string xVoice, string xUserName, string xPassword, string xToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveComplains", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> ReceiveComplainsAsync(string xCustomerPhone, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, string xVideo, string xVoice, string xUserName, string xPassword, string xToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveComplainsAndroid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> ReceiveComplainsAndroidAsync(string xCustomerPhone, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, string xVideo, string xVoice, string xUserName, string xPassword, string xToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveComplainsAndroidBase64", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> ReceiveComplainsAndroidBase64Async(string xCustomerPhone, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, string xVideo, string xVoice, string xUserName, string xPassword, string xToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchMobileComplains", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.Complains[]> SearchMobileComplainsAsync(string xCustomerPhone, string xProblemsNumber, string xProblemStatusID, string xPageIndex, string xPageSize, string xUserName, string xPassword, string xToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchMobileComplainsByNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ComplainsByNumber[]> SearchMobileComplainsByNumberAsync(string xCustomerPhone, string xProblemsNumber, string xUserName, string xPassword, string xToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReOpenExceutedComplaint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> ReOpenExceutedComplaintAsync(string xProblemsNumber, string xCustomerPhone, string xComment, string xUserName, string xPassword, string xToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotApprovedComplainsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ListNotApprovedComplains[]> NotApprovedComplainsListAsync(string xCustomerPhone, string xPageIndex, string xPageSize, string xUserName, string xPassword, string xToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitComplainEvaluation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> SubmitComplainEvaluationAsync(string xProblemsNumber, string xCustomerPhone, string xEvalValue, string xUserName, string xPassword, string xToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotApprovedComplainsDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AmanaIntegration.NotApprovedComplainsDetailsClass[]> NotApprovedComplainsDetailsAsync(string xProblemID, string xCustomerPhone, string xUserName, string xPassword, string xToken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReplyMessages
    {
        
        private int codeField;
        
        private string messageArField;
        
        private string messageEnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageAr
        {
            get
            {
                return this.messageArField;
            }
            set
            {
                this.messageArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MessageEn
        {
            get
            {
                return this.messageEnField;
            }
            set
            {
                this.messageEnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NotApprovedComplainsDetailsClass
    {
        
        private string problem_MobileImageField;
        
        private string problem_MobileVideoField;
        
        private string problem_MobileVoiceField;
        
        private string problem_ContainsMobileImageField;
        
        private string problem_ContainsMobileVideoField;
        
        private string problem_ContainsMobileVoiceField;
        
        private string problem_DescField;
        
        private string problem_LatitudeField;
        
        private string problem_LongitudeField;
        
        private string problem_CreatedDateField;
        
        private string ticket_AddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Problem_MobileImage
        {
            get
            {
                return this.problem_MobileImageField;
            }
            set
            {
                this.problem_MobileImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Problem_MobileVideo
        {
            get
            {
                return this.problem_MobileVideoField;
            }
            set
            {
                this.problem_MobileVideoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Problem_MobileVoice
        {
            get
            {
                return this.problem_MobileVoiceField;
            }
            set
            {
                this.problem_MobileVoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Problem_ContainsMobileImage
        {
            get
            {
                return this.problem_ContainsMobileImageField;
            }
            set
            {
                this.problem_ContainsMobileImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Problem_ContainsMobileVideo
        {
            get
            {
                return this.problem_ContainsMobileVideoField;
            }
            set
            {
                this.problem_ContainsMobileVideoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Problem_ContainsMobileVoice
        {
            get
            {
                return this.problem_ContainsMobileVoiceField;
            }
            set
            {
                this.problem_ContainsMobileVoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Problem_Desc
        {
            get
            {
                return this.problem_DescField;
            }
            set
            {
                this.problem_DescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Problem_Latitude
        {
            get
            {
                return this.problem_LatitudeField;
            }
            set
            {
                this.problem_LatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Problem_Longitude
        {
            get
            {
                return this.problem_LongitudeField;
            }
            set
            {
                this.problem_LongitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Problem_CreatedDate
        {
            get
            {
                return this.problem_CreatedDateField;
            }
            set
            {
                this.problem_CreatedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Ticket_Address
        {
            get
            {
                return this.ticket_AddressField;
            }
            set
            {
                this.ticket_AddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListNotApprovedComplains
    {
        
        private int problemIDField;
        
        private string short_DescField;
        
        private string problem_DescField;
        
        private string ticket_AddressField;
        
        private string customerContact_ContactDescField;
        
        private string problem_CreatedDateField;
        
        private string problem_CreatedDateEnField;
        
        private string problem_CreatedTimeField;
        
        private string problem_CreatedTimeEnField;
        
        private string statusDescArField;
        
        private string statusDescEnField;
        
        private int itemsCountField;
        
        private int totalComplainsCountField;
        
        private string problem_LatitudeField;
        
        private string problem_LongitudeField;
        
        private int problem_FileExistsField;
        
        private string problem_MobileImageField;
        
        private string problem_MobileVideoField;
        
        private string problem_MobileVoiceField;
        
        private string problem_ContainsMobileImageField;
        
        private string problem_ContainsMobileVideoField;
        
        private string problem_ContainsMobileVoiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ProblemID
        {
            get
            {
                return this.problemIDField;
            }
            set
            {
                this.problemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Short_Desc
        {
            get
            {
                return this.short_DescField;
            }
            set
            {
                this.short_DescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Problem_Desc
        {
            get
            {
                return this.problem_DescField;
            }
            set
            {
                this.problem_DescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Ticket_Address
        {
            get
            {
                return this.ticket_AddressField;
            }
            set
            {
                this.ticket_AddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CustomerContact_ContactDesc
        {
            get
            {
                return this.customerContact_ContactDescField;
            }
            set
            {
                this.customerContact_ContactDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Problem_CreatedDate
        {
            get
            {
                return this.problem_CreatedDateField;
            }
            set
            {
                this.problem_CreatedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Problem_CreatedDateEn
        {
            get
            {
                return this.problem_CreatedDateEnField;
            }
            set
            {
                this.problem_CreatedDateEnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Problem_CreatedTime
        {
            get
            {
                return this.problem_CreatedTimeField;
            }
            set
            {
                this.problem_CreatedTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Problem_CreatedTimeEn
        {
            get
            {
                return this.problem_CreatedTimeEnField;
            }
            set
            {
                this.problem_CreatedTimeEnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string StatusDescAr
        {
            get
            {
                return this.statusDescArField;
            }
            set
            {
                this.statusDescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string StatusDescEn
        {
            get
            {
                return this.statusDescEnField;
            }
            set
            {
                this.statusDescEnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int ItemsCount
        {
            get
            {
                return this.itemsCountField;
            }
            set
            {
                this.itemsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int TotalComplainsCount
        {
            get
            {
                return this.totalComplainsCountField;
            }
            set
            {
                this.totalComplainsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Problem_Latitude
        {
            get
            {
                return this.problem_LatitudeField;
            }
            set
            {
                this.problem_LatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Problem_Longitude
        {
            get
            {
                return this.problem_LongitudeField;
            }
            set
            {
                this.problem_LongitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int Problem_FileExists
        {
            get
            {
                return this.problem_FileExistsField;
            }
            set
            {
                this.problem_FileExistsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Problem_MobileImage
        {
            get
            {
                return this.problem_MobileImageField;
            }
            set
            {
                this.problem_MobileImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Problem_MobileVideo
        {
            get
            {
                return this.problem_MobileVideoField;
            }
            set
            {
                this.problem_MobileVideoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Problem_MobileVoice
        {
            get
            {
                return this.problem_MobileVoiceField;
            }
            set
            {
                this.problem_MobileVoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Problem_ContainsMobileImage
        {
            get
            {
                return this.problem_ContainsMobileImageField;
            }
            set
            {
                this.problem_ContainsMobileImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Problem_ContainsMobileVideo
        {
            get
            {
                return this.problem_ContainsMobileVideoField;
            }
            set
            {
                this.problem_ContainsMobileVideoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Problem_ContainsMobileVoice
        {
            get
            {
                return this.problem_ContainsMobileVoiceField;
            }
            set
            {
                this.problem_ContainsMobileVoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ComplainsByNumber
    {
        
        private string problem_ContainsMobileImageField;
        
        private string problem_ContainsMobileVideoField;
        
        private string problem_ContainsMobileVoiceField;
        
        private int problem_MobileEvalValueField;
        
        private string problem_MobileImageField;
        
        private string problem_MobileVideoField;
        
        private string problem_MobileVoiceField;
        
        private string problem_ExecutionImageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Problem_ContainsMobileImage
        {
            get
            {
                return this.problem_ContainsMobileImageField;
            }
            set
            {
                this.problem_ContainsMobileImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Problem_ContainsMobileVideo
        {
            get
            {
                return this.problem_ContainsMobileVideoField;
            }
            set
            {
                this.problem_ContainsMobileVideoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Problem_ContainsMobileVoice
        {
            get
            {
                return this.problem_ContainsMobileVoiceField;
            }
            set
            {
                this.problem_ContainsMobileVoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Problem_MobileEvalValue
        {
            get
            {
                return this.problem_MobileEvalValueField;
            }
            set
            {
                this.problem_MobileEvalValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Problem_MobileImage
        {
            get
            {
                return this.problem_MobileImageField;
            }
            set
            {
                this.problem_MobileImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Problem_MobileVideo
        {
            get
            {
                return this.problem_MobileVideoField;
            }
            set
            {
                this.problem_MobileVideoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Problem_MobileVoice
        {
            get
            {
                return this.problem_MobileVoiceField;
            }
            set
            {
                this.problem_MobileVoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Problem_ExecutionImage
        {
            get
            {
                return this.problem_ExecutionImageField;
            }
            set
            {
                this.problem_ExecutionImageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Complains
    {
        
        private string short_DescField;
        
        private string problem_DescField;
        
        private string organization_DescArField;
        
        private string subCategory_DescArField;
        
        private string ticket_AddressField;
        
        private string customerContact_ContactDescField;
        
        private string district_DescArField;
        
        private string street_DescArField;
        
        private string problem_CreatedDateField;
        
        private string problem_ClosedDateField;
        
        private string problem_ProblemNumberField;
        
        private string category_DescArField;
        
        private string problemStatus_DescArField;
        
        private string problemStatus_DescEnField;
        
        private int problemStatusIDField;
        
        private int itemsCountField;
        
        private int totalComplainsCountField;
        
        private string problem_LatitudeField;
        
        private string problem_LongitudeField;
        
        private string problem_MobileImagePathField;
        
        private string problem_EvalValueField;
        
        private string problem_containsmobileimageField;
        
        private string problem_containsmobilevideoField;
        
        private string problem_containsmobilevoiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Short_Desc
        {
            get
            {
                return this.short_DescField;
            }
            set
            {
                this.short_DescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Problem_Desc
        {
            get
            {
                return this.problem_DescField;
            }
            set
            {
                this.problem_DescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Organization_DescAr
        {
            get
            {
                return this.organization_DescArField;
            }
            set
            {
                this.organization_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SubCategory_DescAr
        {
            get
            {
                return this.subCategory_DescArField;
            }
            set
            {
                this.subCategory_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Ticket_Address
        {
            get
            {
                return this.ticket_AddressField;
            }
            set
            {
                this.ticket_AddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CustomerContact_ContactDesc
        {
            get
            {
                return this.customerContact_ContactDescField;
            }
            set
            {
                this.customerContact_ContactDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string District_DescAr
        {
            get
            {
                return this.district_DescArField;
            }
            set
            {
                this.district_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Street_DescAr
        {
            get
            {
                return this.street_DescArField;
            }
            set
            {
                this.street_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Problem_CreatedDate
        {
            get
            {
                return this.problem_CreatedDateField;
            }
            set
            {
                this.problem_CreatedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Problem_ClosedDate
        {
            get
            {
                return this.problem_ClosedDateField;
            }
            set
            {
                this.problem_ClosedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Problem_ProblemNumber
        {
            get
            {
                return this.problem_ProblemNumberField;
            }
            set
            {
                this.problem_ProblemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Category_DescAr
        {
            get
            {
                return this.category_DescArField;
            }
            set
            {
                this.category_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ProblemStatus_DescAr
        {
            get
            {
                return this.problemStatus_DescArField;
            }
            set
            {
                this.problemStatus_DescArField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ProblemStatus_DescEn
        {
            get
            {
                return this.problemStatus_DescEnField;
            }
            set
            {
                this.problemStatus_DescEnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int ProblemStatusID
        {
            get
            {
                return this.problemStatusIDField;
            }
            set
            {
                this.problemStatusIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int ItemsCount
        {
            get
            {
                return this.itemsCountField;
            }
            set
            {
                this.itemsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int TotalComplainsCount
        {
            get
            {
                return this.totalComplainsCountField;
            }
            set
            {
                this.totalComplainsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Problem_Latitude
        {
            get
            {
                return this.problem_LatitudeField;
            }
            set
            {
                this.problem_LatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Problem_Longitude
        {
            get
            {
                return this.problem_LongitudeField;
            }
            set
            {
                this.problem_LongitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Problem_MobileImagePath
        {
            get
            {
                return this.problem_MobileImagePathField;
            }
            set
            {
                this.problem_MobileImagePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Problem_EvalValue
        {
            get
            {
                return this.problem_EvalValueField;
            }
            set
            {
                this.problem_EvalValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string problem_containsmobileimage
        {
            get
            {
                return this.problem_containsmobileimageField;
            }
            set
            {
                this.problem_containsmobileimageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string problem_containsmobilevideo
        {
            get
            {
                return this.problem_containsmobilevideoField;
            }
            set
            {
                this.problem_containsmobilevideoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string problem_containsmobilevoice
        {
            get
            {
                return this.problem_containsmobilevoiceField;
            }
            set
            {
                this.problem_containsmobilevoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubCategory
    {
        
        private int subCategoryIDField;
        
        private string subCategoryDescField;
        
        private string subCategoryDescEnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SubCategoryID
        {
            get
            {
                return this.subCategoryIDField;
            }
            set
            {
                this.subCategoryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubCategoryDesc
        {
            get
            {
                return this.subCategoryDescField;
            }
            set
            {
                this.subCategoryDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SubCategoryDescEn
        {
            get
            {
                return this.subCategoryDescEnField;
            }
            set
            {
                this.subCategoryDescEnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Category
    {
        
        private int categoryIDField;
        
        private string categoryDescField;
        
        private string categoryDescEnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CategoryID
        {
            get
            {
                return this.categoryIDField;
            }
            set
            {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CategoryDesc
        {
            get
            {
                return this.categoryDescField;
            }
            set
            {
                this.categoryDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CategoryDescEn
        {
            get
            {
                return this.categoryDescEnField;
            }
            set
            {
                this.categoryDescEnField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface AmanaReceiverMobileSoapChannel : AmanaIntegration.AmanaReceiverMobileSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class AmanaReceiverMobileSoapClient : System.ServiceModel.ClientBase<AmanaIntegration.AmanaReceiverMobileSoap>, AmanaIntegration.AmanaReceiverMobileSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AmanaReceiverMobileSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AmanaReceiverMobileSoapClient.GetBindingForEndpoint(endpointConfiguration), AmanaReceiverMobileSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AmanaReceiverMobileSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AmanaReceiverMobileSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AmanaReceiverMobileSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AmanaReceiverMobileSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AmanaReceiverMobileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> ActivateMobileNumberAsync(string xCutomerName, string xCustomerPhone, string xDeviceType, string xUserName, string xPassword, string xToken)
        {
            return base.Channel.ActivateMobileNumberAsync(xCutomerName, xCustomerPhone, xDeviceType, xUserName, xPassword, xToken);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> ReceiveComplaintsNewAsync(string xCustomerPhone, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xAttachmentNo1, string xAttachmentNo1Type, string xAttachmentNo2, string xAttachmentNo2Type, string xAttachmentNo3, string xAttachmentNo3Type, string xUserName, string xPassword, string xToken)
        {
            return base.Channel.ReceiveComplaintsNewAsync(xCustomerPhone, xComplainDescription, xAddressDesc, xLatitude, xLongitude, xAttachmentNo1, xAttachmentNo1Type, xAttachmentNo2, xAttachmentNo2Type, xAttachmentNo3, xAttachmentNo3Type, xUserName, xPassword, xToken);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> SendOTPAsync(string xCutomerName, string xCustomerPhone, string xDeviceType, string xUserName, string xPassword, string xToken)
        {
            return base.Channel.SendOTPAsync(xCutomerName, xCustomerPhone, xDeviceType, xUserName, xPassword, xToken);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.Category[]> CategoryListAsync(string xUserName, string xPassword)
        {
            return base.Channel.CategoryListAsync(xUserName, xPassword);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.SubCategory[]> SubCategoryListAsync(string xCategoryID, string xUserName, string xPassword)
        {
            return base.Channel.SubCategoryListAsync(xCategoryID, xUserName, xPassword);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> TestInsertNotificationAsync(string xNotificationArabic, string xNotificationEnglish, string xExpiryDate)
        {
            return base.Channel.TestInsertNotificationAsync(xNotificationArabic, xNotificationEnglish, xExpiryDate);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> SendNotificationAsync(string xUserName, string xPassword)
        {
            return base.Channel.SendNotificationAsync(xUserName, xPassword);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> CheckOTPAsync(string xCustomerPhone, string xOTP, string xUserName, string xPassword, string xToken)
        {
            return base.Channel.CheckOTPAsync(xCustomerPhone, xOTP, xUserName, xPassword, xToken);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> DeactivateMobileNumberAsync(string xCustomerPhone, string xUserName, string xPassword)
        {
            return base.Channel.DeactivateMobileNumberAsync(xCustomerPhone, xUserName, xPassword);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> CheckUserIsBlockedAsync(string xCustomerPhone)
        {
            return base.Channel.CheckUserIsBlockedAsync(xCustomerPhone);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> ReceiveComplainsWSEAsync(string xCustomerPhone, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, string xVideo, string xVoice, string xUserName, string xPassword, string xToken)
        {
            return base.Channel.ReceiveComplainsWSEAsync(xCustomerPhone, xComplainDescription, xAddressDesc, xLatitude, xLongitude, xImage, xVideo, xVoice, xUserName, xPassword, xToken);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> ReceiveComplainsAsync(string xCustomerPhone, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, string xVideo, string xVoice, string xUserName, string xPassword, string xToken)
        {
            return base.Channel.ReceiveComplainsAsync(xCustomerPhone, xComplainDescription, xAddressDesc, xLatitude, xLongitude, xImage, xVideo, xVoice, xUserName, xPassword, xToken);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> ReceiveComplainsAndroidAsync(string xCustomerPhone, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, string xVideo, string xVoice, string xUserName, string xPassword, string xToken)
        {
            return base.Channel.ReceiveComplainsAndroidAsync(xCustomerPhone, xComplainDescription, xAddressDesc, xLatitude, xLongitude, xImage, xVideo, xVoice, xUserName, xPassword, xToken);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> ReceiveComplainsAndroidBase64Async(string xCustomerPhone, string xComplainDescription, string xAddressDesc, string xLatitude, string xLongitude, string xImage, string xVideo, string xVoice, string xUserName, string xPassword, string xToken)
        {
            return base.Channel.ReceiveComplainsAndroidBase64Async(xCustomerPhone, xComplainDescription, xAddressDesc, xLatitude, xLongitude, xImage, xVideo, xVoice, xUserName, xPassword, xToken);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.Complains[]> SearchMobileComplainsAsync(string xCustomerPhone, string xProblemsNumber, string xProblemStatusID, string xPageIndex, string xPageSize, string xUserName, string xPassword, string xToken)
        {
            return base.Channel.SearchMobileComplainsAsync(xCustomerPhone, xProblemsNumber, xProblemStatusID, xPageIndex, xPageSize, xUserName, xPassword, xToken);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ComplainsByNumber[]> SearchMobileComplainsByNumberAsync(string xCustomerPhone, string xProblemsNumber, string xUserName, string xPassword, string xToken)
        {
            return base.Channel.SearchMobileComplainsByNumberAsync(xCustomerPhone, xProblemsNumber, xUserName, xPassword, xToken);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> ReOpenExceutedComplaintAsync(string xProblemsNumber, string xCustomerPhone, string xComment, string xUserName, string xPassword, string xToken)
        {
            return base.Channel.ReOpenExceutedComplaintAsync(xProblemsNumber, xCustomerPhone, xComment, xUserName, xPassword, xToken);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ListNotApprovedComplains[]> NotApprovedComplainsListAsync(string xCustomerPhone, string xPageIndex, string xPageSize, string xUserName, string xPassword, string xToken)
        {
            return base.Channel.NotApprovedComplainsListAsync(xCustomerPhone, xPageIndex, xPageSize, xUserName, xPassword, xToken);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.ReplyMessages> SubmitComplainEvaluationAsync(string xProblemsNumber, string xCustomerPhone, string xEvalValue, string xUserName, string xPassword, string xToken)
        {
            return base.Channel.SubmitComplainEvaluationAsync(xProblemsNumber, xCustomerPhone, xEvalValue, xUserName, xPassword, xToken);
        }
        
        public System.Threading.Tasks.Task<AmanaIntegration.NotApprovedComplainsDetailsClass[]> NotApprovedComplainsDetailsAsync(string xProblemID, string xCustomerPhone, string xUserName, string xPassword, string xToken)
        {
            return base.Channel.NotApprovedComplainsDetailsAsync(xProblemID, xCustomerPhone, xUserName, xPassword, xToken);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AmanaReceiverMobileSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AmanaReceiverMobileSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AmanaReceiverMobileSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://call940.sa/MobileAPItest/AmanaReceiverMobile.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AmanaReceiverMobileSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://call940.sa/MobileAPItest/AmanaReceiverMobile.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AmanaReceiverMobileSoap,
            
            AmanaReceiverMobileSoap12,
        }
    }
}
