// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RM.Competitions.Repositories;

#nullable disable

namespace RM.Competitions.Migrations
{
    [DbContext(typeof(GardensCompetitionContext))]
    partial class GardensCompetitionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RM.EF.Competitions.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompetitorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorId");

                    b.HasIndex("TypeId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("RM.EF.Competitions.AttachmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcceptedExtention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxCount")
                        .HasColumnType("int");

                    b.Property<int?>("MinCount")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AttachmentType", (string)null);
                });

            modelBuilder.Entity("RM.EF.Competitions.Competitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<int?>("CandidatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CandidatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommercialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ComplateAttachDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCandidated")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCompleteAttachFile")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLecturer")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTeam")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileDoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RepresentsUniversity")
                        .HasColumnType("bit");

                    b.Property<string>("SpecializationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("UniversityApprovalDoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniversityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Competitors");
                });

            modelBuilder.Entity("RM.EF.Competitions.CompetitorsType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompetitorsType", (string)null);
                });

            modelBuilder.Entity("RM.EF.Competitions.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompetitorId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("RM.EF.Competitions.Attachment", b =>
                {
                    b.HasOne("RM.EF.Competitions.Competitor", "Competitor")
                        .WithMany("Attachments")
                        .HasForeignKey("CompetitorId")
                        .HasConstraintName("FK_Attachments_Competitors");

                    b.HasOne("RM.EF.Competitions.AttachmentType", "Type")
                        .WithMany("Attachments")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Attachments_AttachmentType");

                    b.Navigation("Competitor");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("RM.EF.Competitions.Competitor", b =>
                {
                    b.HasOne("RM.EF.Competitions.CompetitorsType", "Type")
                        .WithMany("Competitors")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Competitors_CompetitorsType");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("RM.EF.Competitions.TeamMember", b =>
                {
                    b.HasOne("RM.EF.Competitions.Competitor", "Competitor")
                        .WithMany("TeamMembers")
                        .HasForeignKey("CompetitorId")
                        .HasConstraintName("FK_TeamMembers_Competitors");

                    b.Navigation("Competitor");
                });

            modelBuilder.Entity("RM.EF.Competitions.AttachmentType", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("RM.EF.Competitions.Competitor", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("RM.EF.Competitions.CompetitorsType", b =>
                {
                    b.Navigation("Competitors");
                });
#pragma warning restore 612, 618
        }
    }
}
