//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDataSvc
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpenDataStats", Namespace="http://schemas.datacontract.org/2004/07/Opendata.Webservice.Entities")]
    public partial class OpenDataStats : object
    {
        
        private string NameField;
        
        private string NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OpenDataSvc.IOpendataServices")]
    public interface IOpendataServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpendataServices/InsertRequest", ReplyAction="http://tempuri.org/IOpendataServices/InsertRequestResponse")]
        bool InsertRequest(string Name, string Email, string Mobile, string Address, string Details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpendataServices/InsertRequest", ReplyAction="http://tempuri.org/IOpendataServices/InsertRequestResponse")]
        System.Threading.Tasks.Task<bool> InsertRequestAsync(string Name, string Email, string Mobile, string Address, string Details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpendataServices/GetOpenDataStats", ReplyAction="http://tempuri.org/IOpendataServices/GetOpenDataStatsResponse")]
        OpenDataSvc.OpenDataStats[] GetOpenDataStats();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpendataServices/GetOpenDataStats", ReplyAction="http://tempuri.org/IOpendataServices/GetOpenDataStatsResponse")]
        System.Threading.Tasks.Task<OpenDataSvc.OpenDataStats[]> GetOpenDataStatsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IOpendataServicesChannel : OpenDataSvc.IOpendataServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class OpendataServicesClient : System.ServiceModel.ClientBase<OpenDataSvc.IOpendataServices>, OpenDataSvc.IOpendataServices
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OpendataServicesClient() : 
                base(OpendataServicesClient.GetDefaultBinding(), OpendataServicesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IOpendataServices.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpendataServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(OpendataServicesClient.GetBindingForEndpoint(endpointConfiguration), OpendataServicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpendataServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OpendataServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpendataServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OpendataServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpendataServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool InsertRequest(string Name, string Email, string Mobile, string Address, string Details)
        {
            return base.Channel.InsertRequest(Name, Email, Mobile, Address, Details);
        }
        
        public System.Threading.Tasks.Task<bool> InsertRequestAsync(string Name, string Email, string Mobile, string Address, string Details)
        {
            return base.Channel.InsertRequestAsync(Name, Email, Mobile, Address, Details);
        }
        
        public OpenDataSvc.OpenDataStats[] GetOpenDataStats()
        {
            return base.Channel.GetOpenDataStats();
        }
        
        public System.Threading.Tasks.Task<OpenDataSvc.OpenDataStats[]> GetOpenDataStatsAsync()
        {
            return base.Channel.GetOpenDataStatsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOpendataServices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOpendataServices))
            {
                return new System.ServiceModel.EndpointAddress("http://test1.alriyadh.gov.sa/opendata/OpendataServices.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OpendataServicesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IOpendataServices);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OpendataServicesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IOpendataServices);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IOpendataServices,
        }
    }
}
