//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactMayorIntegration
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSComplaint", Namespace="http://schemas.datacontract.org/2004/07/ContactMayor.Webservice")]
    public partial class WSComplaint : object
    {
        
        private string DetailsField;
        
        private string EmailField;
        
        private long IDField;
        
        private string ImageURLField;
        
        private string IqamaIDField;
        
        private string MobileField;
        
        private string NameField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL
        {
            get
            {
                return this.ImageURLField;
            }
            set
            {
                this.ImageURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IqamaID
        {
            get
            {
                return this.IqamaIDField;
            }
            set
            {
                this.IqamaIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSComplaintRole", Namespace="http://schemas.datacontract.org/2004/07/ContactMayor.Webservice")]
    public partial class WSComplaintRole : object
    {
        
        private string CommentField;
        
        private string CreatedByField;
        
        private System.DateTime CreatedOnField;
        
        private string RoleNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName
        {
            get
            {
                return this.RoleNameField;
            }
            set
            {
                this.RoleNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSComment", Namespace="http://schemas.datacontract.org/2004/07/ContactMayor.Webservice")]
    public partial class WSComment : object
    {
        
        private string CreatedByField;
        
        private System.DateTime CreatedOnField;
        
        private string TextField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContactMayorIntegration.IContactMayorService")]
    public interface IContactMayorService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactMayorService/InsertComplaint", ReplyAction="http://tempuri.org/IContactMayorService/InsertComplaintResponse")]
        long InsertComplaint(ContactMayorIntegration.WSComplaint Complaint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactMayorService/InsertComplaint", ReplyAction="http://tempuri.org/IContactMayorService/InsertComplaintResponse")]
        System.Threading.Tasks.Task<long> InsertComplaintAsync(ContactMayorIntegration.WSComplaint Complaint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactMayorService/GetComments", ReplyAction="http://tempuri.org/IContactMayorService/GetCommentsResponse")]
        ContactMayorIntegration.WSComplaintRole[] GetComments(long ComplaintID, string Mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactMayorService/GetComments", ReplyAction="http://tempuri.org/IContactMayorService/GetCommentsResponse")]
        System.Threading.Tasks.Task<ContactMayorIntegration.WSComplaintRole[]> GetCommentsAsync(long ComplaintID, string Mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactMayorService/GetReplies", ReplyAction="http://tempuri.org/IContactMayorService/GetRepliesResponse")]
        ContactMayorIntegration.WSComment[] GetReplies(long ComplaintID, string Mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactMayorService/GetReplies", ReplyAction="http://tempuri.org/IContactMayorService/GetRepliesResponse")]
        System.Threading.Tasks.Task<ContactMayorIntegration.WSComment[]> GetRepliesAsync(long ComplaintID, string Mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactMayorService/GetComplaint", ReplyAction="http://tempuri.org/IContactMayorService/GetComplaintResponse")]
        ContactMayorIntegration.WSComplaint GetComplaint(long ComplaintID, string Mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactMayorService/GetComplaint", ReplyAction="http://tempuri.org/IContactMayorService/GetComplaintResponse")]
        System.Threading.Tasks.Task<ContactMayorIntegration.WSComplaint> GetComplaintAsync(long ComplaintID, string Mobile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IContactMayorServiceChannel : ContactMayorIntegration.IContactMayorService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class ContactMayorServiceClient : System.ServiceModel.ClientBase<ContactMayorIntegration.IContactMayorService>, ContactMayorIntegration.IContactMayorService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ContactMayorServiceClient() : 
                base(ContactMayorServiceClient.GetDefaultBinding(), ContactMayorServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IContactMayorService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContactMayorServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ContactMayorServiceClient.GetBindingForEndpoint(endpointConfiguration), ContactMayorServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContactMayorServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ContactMayorServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContactMayorServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ContactMayorServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContactMayorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public long InsertComplaint(ContactMayorIntegration.WSComplaint Complaint)
        {
            return base.Channel.InsertComplaint(Complaint);
        }
        
        public System.Threading.Tasks.Task<long> InsertComplaintAsync(ContactMayorIntegration.WSComplaint Complaint)
        {
            return base.Channel.InsertComplaintAsync(Complaint);
        }
        
        public ContactMayorIntegration.WSComplaintRole[] GetComments(long ComplaintID, string Mobile)
        {
            return base.Channel.GetComments(ComplaintID, Mobile);
        }
        
        public System.Threading.Tasks.Task<ContactMayorIntegration.WSComplaintRole[]> GetCommentsAsync(long ComplaintID, string Mobile)
        {
            return base.Channel.GetCommentsAsync(ComplaintID, Mobile);
        }
        
        public ContactMayorIntegration.WSComment[] GetReplies(long ComplaintID, string Mobile)
        {
            return base.Channel.GetReplies(ComplaintID, Mobile);
        }
        
        public System.Threading.Tasks.Task<ContactMayorIntegration.WSComment[]> GetRepliesAsync(long ComplaintID, string Mobile)
        {
            return base.Channel.GetRepliesAsync(ComplaintID, Mobile);
        }
        
        public ContactMayorIntegration.WSComplaint GetComplaint(long ComplaintID, string Mobile)
        {
            return base.Channel.GetComplaint(ComplaintID, Mobile);
        }
        
        public System.Threading.Tasks.Task<ContactMayorIntegration.WSComplaint> GetComplaintAsync(long ComplaintID, string Mobile)
        {
            return base.Channel.GetComplaintAsync(ComplaintID, Mobile);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IContactMayorService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IContactMayorService))
            {
                return new System.ServiceModel.EndpointAddress("http://10.120.6.34:777/ContactMayorService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ContactMayorServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IContactMayorService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ContactMayorServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IContactMayorService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IContactMayorService,
        }
    }
}
